import type { Job } from '../../types/job';
import type { Npc } from '../../types/npc';
import type { OrganizationDefinition, OrganizationHistoryEntry, OrganizationJobModifier, OrganizationLocationModifier, OrganizationPanelState, OrganizationRuntimeState, OrganizationStatus, OrganizationUniversityModifier, OrganizationWorldState } from '../../types/organization';
import type { CityId, JobId, LocationId, UniversityId } from '../../types/ids';

const STATUS_LABELS: Record<OrganizationStatus, string> = { growing: 'Рост', stable: 'Стабильно', strained: 'Напряжение', critical: 'Кризис' };
const STATUS_DESCRIPTIONS: Record<OrganizationStatus, string> = { growing: 'Организация расширяется, укрепляет штат и улучшает условия.', stable: 'Работа идёт без серьёзных сбоев.', strained: 'Не хватает людей или денег. Нагрузка и цены растут.', critical: 'Организация сокращает расходы и может временно закрываться.' };
function hashString(value: string): number { let hash = 2166136261; for (let index = 0; index < value.length; index += 1) { hash ^= value.charCodeAt(index); hash = Math.imul(hash, 16777619); } return hash >>> 0; }
function clamp(value: number, min: number, max: number): number { return Math.max(min, Math.min(max, value)); }
function createRuntime(definition: OrganizationDefinition, day: number): OrganizationRuntimeState { return { id: definition.id, budget: Math.round(definition.baseWeeklyExpenses * 1.5), reputation: 55, demandIndex: 100, staffCount: definition.targetStaff, targetStaff: definition.targetStaff, status: 'stable', lastProcessedDay: day }; }
export function createInitialOrganizationState(input: { seed: number; day: number; definitions: OrganizationDefinition[] }): OrganizationWorldState { return { version: 1, seed: Math.max(1, Math.floor(input.seed)), lastProcessedDay: Math.max(1, Math.floor(input.day)), organizations: Object.fromEntries(input.definitions.map((definition) => [String(definition.id), createRuntime(definition, input.day)])), history: [] }; }
export function normalizeOrganizationState(input: { value: unknown; seed: number; day: number; definitions: OrganizationDefinition[] }): OrganizationWorldState {
  const initial = createInitialOrganizationState(input); if (!input.value || typeof input.value !== 'object') return initial;
  const candidate = input.value as Partial<OrganizationWorldState>; const rawStates = candidate.organizations && typeof candidate.organizations === 'object' ? candidate.organizations : {}; const organizations: Record<string, OrganizationRuntimeState> = {};
  for (const definition of input.definitions) { const fallback = initial.organizations[String(definition.id)]; const raw = rawStates[String(definition.id)]; if (!raw || typeof raw !== 'object') { organizations[String(definition.id)] = fallback; continue; } const status: OrganizationStatus = raw.status === 'growing' || raw.status === 'strained' || raw.status === 'critical' ? raw.status : 'stable'; organizations[String(definition.id)] = { id: definition.id, budget: clamp(Number(raw.budget ?? fallback.budget), -500_000, 2_000_000), reputation: clamp(Number(raw.reputation ?? fallback.reputation), 0, 100), demandIndex: clamp(Number(raw.demandIndex ?? fallback.demandIndex), 55, 150), staffCount: Math.max(0, Math.floor(Number(raw.staffCount ?? fallback.staffCount))), targetStaff: definition.targetStaff, status, lastProcessedDay: Math.min(input.day, Math.max(1, Math.floor(Number(raw.lastProcessedDay ?? input.day)))), closedUntilDay: typeof raw.closedUntilDay === 'number' ? Math.max(1, Math.floor(raw.closedUntilDay)) : undefined }; }
  return { version: 1, seed: typeof candidate.seed === 'number' ? Math.max(1, Math.floor(candidate.seed)) : initial.seed, lastProcessedDay: typeof candidate.lastProcessedDay === 'number' ? Math.min(input.day, Math.max(1, Math.floor(candidate.lastProcessedDay))) : input.day, organizations, history: Array.isArray(candidate.history) ? candidate.history.slice(0, 100) : [] };
}
function classifyStatus(input: { budget: number; reputation: number; staffingRatio: number }): OrganizationStatus { if (input.budget < -20_000 || input.reputation < 22 || input.staffingRatio < 0.35) return 'critical'; if (input.budget < 35_000 || input.reputation < 42 || input.staffingRatio < 0.7) return 'strained'; if (input.budget > 180_000 && input.reputation >= 65 && input.staffingRatio >= 0.9) return 'growing'; return 'stable'; }
function historyEntry(input: Omit<OrganizationHistoryEntry, 'id'>): OrganizationHistoryEntry { return { ...input, id: `organization_${input.kind}_${String(input.organizationId)}_${input.day}` }; }
function countStaff(definition: OrganizationDefinition, npcs: Npc[], playerJobLocationId?: LocationId): number { const npcStaff = npcs.filter((npc) => npc.employment?.locationId === definition.locationId).length; return npcStaff + (playerJobLocationId === definition.locationId ? 1 : 0); }
function countStudents(definition: OrganizationDefinition, npcs: Npc[], getNpcCityId: (npc: Npc) => CityId | undefined): number { return npcs.filter((npc) => npc.activityProfile === 'student' && getNpcCityId(npc) === definition.cityId).length; }
function maybeLayOffNpc(input: { definition: OrganizationDefinition; npcs: Npc[]; seed: number; day: number }): { npcs: Npc[]; event?: OrganizationHistoryEntry } {
  const staff = input.npcs.filter((npc) => npc.employment?.locationId === input.definition.locationId).sort((first, second) => first.life.reliability - second.life.reliability); if (staff.length <= 1) return { npcs: input.npcs }; const roll = hashString(`${input.seed}:${String(input.definition.id)}:${input.day}:layoff`) % 100; if (roll >= 55) return { npcs: input.npcs }; const dismissed = staff[0]; const nextNpc: Npc = { ...dismissed, activityProfile: 'unemployed', employment: undefined, life: { ...dismissed.life, jobSearchDays: 1, warningCount: 0, lastOutcome: { day: input.day, kind: 'lost_job', text: `Потерял работу: ${input.definition.name}.` } } };
  return { npcs: input.npcs.map((npc) => npc.id === dismissed.id ? nextNpc : npc), event: historyEntry({ day: input.day, kind: 'layoff', organizationId: input.definition.id, cityId: input.definition.cityId, title: 'Сокращение персонала', text: `${input.definition.name}: ${dismissed.firstName} ${dismissed.lastName} потерял работу.` }) };
}
export function processOrganizationTime(input: { state: OrganizationWorldState; fromDay: number; toDay: number; definitions: OrganizationDefinition[]; npcs: Npc[]; playerJobLocationId?: LocationId; playerUniversityId?: UniversityId; getNpcCityId: (npc: Npc) => CityId | undefined }): { state: OrganizationWorldState; npcs: Npc[]; events: OrganizationHistoryEntry[] } {
  if (input.toDay <= input.state.lastProcessedDay) return { state: input.state, npcs: input.npcs, events: [] };
  let organizations = { ...input.state.organizations }; let npcs = input.npcs; const events: OrganizationHistoryEntry[] = []; const startDay = Math.max(input.fromDay + 1, input.state.lastProcessedDay + 1);
  for (let day = startDay; day <= input.toDay; day += 1) {
    for (const definition of input.definitions) {
      const key = String(definition.id); const previous = organizations[key] ?? createRuntime(definition, day);
      if (previous.closedUntilDay !== undefined && day >= previous.closedUntilDay) { organizations[key] = { ...previous, closedUntilDay: undefined, lastProcessedDay: day }; events.push(historyEntry({ day, kind: 'reopened', organizationId: definition.id, cityId: definition.cityId, title: 'Заведение снова открыто', text: `${definition.name} возобновило работу.` })); }
      if ((day - 1) % 7 !== 0 || day === 1) continue;
      const current = organizations[key] ?? previous; const staffCount = definition.kind === 'university' ? Math.max(3, Math.round(countStudents(definition, npcs, input.getNpcCityId) / 4)) : countStaff(definition, npcs, input.playerJobLocationId); const staffingRatio = staffCount / Math.max(1, definition.targetStaff); const demandDrift = (hashString(`${input.state.seed}:${key}:${day}:demand`) % 17) - 8; const demandIndex = definition.kind === 'commerce' ? clamp(current.demandIndex + demandDrift + (current.reputation - 50) * 0.04, 55, 150) : 100; const productivity = clamp(0.5 + staffingRatio * 0.55, 0.45, 1.2); const demandMultiplier = demandIndex / 100; const randomMultiplier = 0.93 + (hashString(`${input.state.seed}:${key}:${day}:flow`) % 15) / 100; const revenue = definition.baseWeeklyRevenue * productivity * demandMultiplier * randomMultiplier; const expenses = definition.baseWeeklyExpenses * (0.88 + Math.min(1.25, staffingRatio) * 0.12); const budget = clamp(current.budget + revenue - expenses, -500_000, 2_000_000); const reputationDelta = staffingRatio < 0.55 ? -4 : budget < 0 ? -3 : budget > 180_000 && staffingRatio >= 0.9 ? 2 : 0; const reputation = clamp(current.reputation + reputationDelta, 0, 100); const status = classifyStatus({ budget, reputation, staffingRatio }); let closedUntilDay = current.closedUntilDay;
      if (definition.kind === 'commerce' && status === 'critical' && closedUntilDay === undefined) { const closureRoll = hashString(`${input.state.seed}:${key}:${day}:closure`) % 100; if (closureRoll < 55) { closedUntilDay = day + 2 + (closureRoll % 3); events.push(historyEntry({ day, kind: 'temporary_closure', organizationId: definition.id, cityId: definition.cityId, title: 'Временное закрытие', text: `${definition.name} закрылось до дня ${closedUntilDay}: не хватает денег или сотрудников.` })); } }
      organizations[key] = { ...current, budget: Math.round(budget), reputation: Math.round(reputation), demandIndex: Math.round(demandIndex), staffCount, targetStaff: definition.targetStaff, status, lastProcessedDay: day, closedUntilDay };
      if (status !== current.status) events.push(historyEntry({ day, kind: 'status_changed', organizationId: definition.id, cityId: definition.cityId, title: `${definition.name}: ${STATUS_LABELS[status]}`, text: STATUS_DESCRIPTIONS[status] }));
      if (definition.kind === 'employer' && status === 'critical' && current.status !== 'critical') { const layoff = maybeLayOffNpc({ definition, npcs, seed: input.state.seed, day }); npcs = layoff.npcs; if (layoff.event) events.push(layoff.event); }
    }
  }
  return { state: { ...input.state, lastProcessedDay: input.toDay, organizations, history: [...events].reverse().concat(input.state.history).slice(0, 100) }, npcs, events };
}
function stateForDefinition(state: OrganizationWorldState, definition: OrganizationDefinition | undefined) { return definition ? state.organizations[String(definition.id)] : undefined; }
export function getOrganizationJobModifier(input: { state: OrganizationWorldState; definition?: OrganizationDefinition }): OrganizationJobModifier { const organization = stateForDefinition(input.state, input.definition); if (!organization) return { workloadMultiplier: 1, wageMultiplier: 1, hiringPressure: 0, openDaysDelta: 0, closedDaysDelta: 0, npcFillChanceDelta: 0 }; const shortage = Math.max(0, organization.targetStaff - organization.staffCount); if (organization.status === 'growing') return { workloadMultiplier: 0.95, wageMultiplier: 1.05, hiringPressure: shortage + 2, openDaysDelta: 3, closedDaysDelta: -2, npcFillChanceDelta: 8, label: 'Компания растёт' }; if (organization.status === 'strained') return { workloadMultiplier: 1.15, wageMultiplier: 1, hiringPressure: shortage + 1, openDaysDelta: 2, closedDaysDelta: -1, npcFillChanceDelta: 4, label: 'Не хватает людей' }; if (organization.status === 'critical') return { workloadMultiplier: 1.25, wageMultiplier: 0.9, hiringPressure: -2, openDaysDelta: -3, closedDaysDelta: 5, npcFillChanceDelta: -12, label: 'Кризис организации' }; return { workloadMultiplier: 1, wageMultiplier: 1, hiringPressure: shortage, openDaysDelta: shortage > 0 ? 1 : 0, closedDaysDelta: 0, npcFillChanceDelta: shortage * 2, label: shortage > 0 ? 'Идёт набор' : undefined }; }
export function getOrganizationUniversityModifier(input: { state: OrganizationWorldState; definition?: OrganizationDefinition }): OrganizationUniversityModifier { const organization = stateForDefinition(input.state, input.definition); if (!organization) return { knowledgeMultiplier: 1, studyLoadDelta: 0 }; if (organization.status === 'growing') return { knowledgeMultiplier: 1.1, studyLoadDelta: -1, label: 'Сильный учебный период' }; if (organization.status === 'strained') return { knowledgeMultiplier: 0.9, studyLoadDelta: 2, label: 'Перегруженный кампус' }; if (organization.status === 'critical') return { knowledgeMultiplier: 0.75, studyLoadDelta: 4, label: 'Кризис университета' }; return { knowledgeMultiplier: 1, studyLoadDelta: 0 }; }
export function getOrganizationLocationModifier(input: { state: OrganizationWorldState; definition?: OrganizationDefinition; day: number }): OrganizationLocationModifier { const organization = stateForDefinition(input.state, input.definition); if (!organization) return { closed: false, priceMultiplier: 1, demandMultiplier: 1 }; const closed = organization.closedUntilDay !== undefined && input.day < organization.closedUntilDay; const statusPrice = organization.status === 'growing' ? 1.04 : organization.status === 'strained' ? 1.08 : organization.status === 'critical' ? 1.15 : 1; return { closed, failure: closed ? `${input.definition?.name ?? 'Заведение'} временно закрыто до дня ${organization.closedUntilDay}.` : undefined, priceMultiplier: statusPrice, demandMultiplier: organization.demandIndex / 100, label: organization.status === 'stable' ? undefined : STATUS_LABELS[organization.status] }; }
export function getBusinessCompetitionMultiplier(input: { state: OrganizationWorldState; definitions: OrganizationDefinition[]; cityId: CityId | undefined; day: number }): number { if (!input.cityId) return 1; const competitors = input.definitions.filter((definition) => definition.kind === 'commerce' && definition.cityId === input.cityId).map((definition) => ({ definition, state: input.state.organizations[String(definition.id)] })).filter((entry): entry is { definition: OrganizationDefinition; state: OrganizationRuntimeState } => Boolean(entry.state)); if (competitors.length === 0) return 1; const competitionStrength = competitors.reduce((sum, entry) => { const closed = entry.state.closedUntilDay !== undefined && input.day < entry.state.closedUntilDay; if (closed) return sum + 0.35; const statusFactor = entry.state.status === 'growing' ? 1.15 : entry.state.status === 'strained' ? 0.85 : entry.state.status === 'critical' ? 0.55 : 1; return sum + (entry.state.demandIndex / 100) * statusFactor; }, 0) / competitors.length; return clamp(1.18 - (competitionStrength - 0.75) * 0.45, 0.82, 1.18); }
export function createOrganizationPanelState(input: { state: OrganizationWorldState; definitions: OrganizationDefinition[]; cityId: CityId }): OrganizationPanelState { const organizations = input.definitions.filter((definition) => definition.cityId === input.cityId).map((definition) => ({ definition, state: input.state.organizations[String(definition.id)] ?? createRuntime(definition, input.state.lastProcessedDay), statusLabel: STATUS_LABELS[input.state.organizations[String(definition.id)]?.status ?? 'stable'], statusDescription: STATUS_DESCRIPTIONS[input.state.organizations[String(definition.id)]?.status ?? 'stable'] })).sort((first, second) => { const weight = { critical: 3, strained: 2, growing: 1, stable: 0 } as const; return weight[second.state.status] - weight[first.state.status]; }); return { organizations, recentChanges: input.state.history.filter((entry) => entry.cityId === input.cityId).slice(0, 8) }; }
export function getOrganizationDefinitionForJob(definitions: OrganizationDefinition[], job: Pick<Job, 'id'> | JobId | undefined) { const jobId = typeof job === 'object' && job ? job.id : job; return definitions.find((definition) => definition.kind === 'employer' && definition.jobIds?.some((id) => id === jobId)); }
